apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-agent
  template:
    metadata:
      labels:
        app: device-agent
    spec:
      containers:
        - name: device-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./device-agent"]
          args: ["-config", "config/config.yaml"]
          volumeMounts:
            - name: kubeconfig
              mountPath: {{ .Values.kubeConfig.containerPath }}
              
      volumes:
        - name: kubeconfig
          hostPath:
            path: {{ .Values.kubeConfig.hostPath }}
            type: File